/*
 * Hyperswitch - API Documentation
 *  ## Get started  Hyperswitch provides a collection of APIs that enable you to process and manage payments. Our APIs accept and return JSON in the HTTP body, and return standard HTTP response codes.  You can consume the APIs directly using your favorite HTTP/REST library.  We have a testing environment referred to \"sandbox\", which you can setup to test API calls without affecting production data. Currently, our sandbox environment is live while our production environment is under development and will be available soon. You can sign up on our Dashboard to get API keys to access Hyperswitch API.  ### Environment  Use the following base URLs when making requests to the APIs:  | Environment   |  Base URL                          | |---------------|------------------------------------| | Sandbox       | <https://sandbox.hyperswitch.io>   | | Production    | <https://api.hyperswitch.io>       |  ## Authentication  When you sign up on our [dashboard](https://app.hyperswitch.io) and create a merchant account, you are given a secret key (also referred as api-key) and a publishable key. You may authenticate all API requests with Hyperswitch server by providing the appropriate key in the request Authorization header.  | Key             |  Description                                                                                  | |-----------------|-----------------------------------------------------------------------------------------------| | api-key         | Private key. Used to authenticate all API requests from your merchant server                  | | publishable key | Unique identifier for your account. Used to authenticate API requests from your app's client  |  Never share your secret api keys. Keep them guarded and secure. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hyperswitch@juspay.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.hyperswitch.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.hyperswitch.client.model.Connector;
import com.hyperswitch.client.model.ConnectorStatus;
import com.hyperswitch.client.model.ConnectorType;
import com.hyperswitch.client.model.CountryAlpha2;
import com.hyperswitch.client.model.FrmConfigs;
import com.hyperswitch.client.model.PaymentMethodsEnabled;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for MerchantConnectorListResponse
 */
public class MerchantConnectorListResponseTest {
    private final MerchantConnectorListResponse model = new MerchantConnectorListResponse();

    /**
     * Model tests for MerchantConnectorListResponse
     */
    @Test
    public void testMerchantConnectorListResponse() {
        // TODO: test MerchantConnectorListResponse
    }

    /**
     * Test the property 'connectorType'
     */
    @Test
    public void connectorTypeTest() {
        // TODO: test connectorType
    }

    /**
     * Test the property 'connectorName'
     */
    @Test
    public void connectorNameTest() {
        // TODO: test connectorName
    }

    /**
     * Test the property 'connectorLabel'
     */
    @Test
    public void connectorLabelTest() {
        // TODO: test connectorLabel
    }

    /**
     * Test the property 'merchantConnectorId'
     */
    @Test
    public void merchantConnectorIdTest() {
        // TODO: test merchantConnectorId
    }

    /**
     * Test the property 'profileId'
     */
    @Test
    public void profileIdTest() {
        // TODO: test profileId
    }

    /**
     * Test the property 'paymentMethodsEnabled'
     */
    @Test
    public void paymentMethodsEnabledTest() {
        // TODO: test paymentMethodsEnabled
    }

    /**
     * Test the property 'testMode'
     */
    @Test
    public void testModeTest() {
        // TODO: test testMode
    }

    /**
     * Test the property 'disabled'
     */
    @Test
    public void disabledTest() {
        // TODO: test disabled
    }

    /**
     * Test the property 'frmConfigs'
     */
    @Test
    public void frmConfigsTest() {
        // TODO: test frmConfigs
    }

    /**
     * Test the property 'businessCountry'
     */
    @Test
    public void businessCountryTest() {
        // TODO: test businessCountry
    }

    /**
     * Test the property 'businessLabel'
     */
    @Test
    public void businessLabelTest() {
        // TODO: test businessLabel
    }

    /**
     * Test the property 'businessSubLabel'
     */
    @Test
    public void businessSubLabelTest() {
        // TODO: test businessSubLabel
    }

    /**
     * Test the property 'applepayVerifiedDomains'
     */
    @Test
    public void applepayVerifiedDomainsTest() {
        // TODO: test applepayVerifiedDomains
    }

    /**
     * Test the property 'pmAuthConfig'
     */
    @Test
    public void pmAuthConfigTest() {
        // TODO: test pmAuthConfig
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

}
