/*
 * Hyperswitch - API Documentation
 *  ## Get started  Hyperswitch provides a collection of APIs that enable you to process and manage payments. Our APIs accept and return JSON in the HTTP body, and return standard HTTP response codes.  You can consume the APIs directly using your favorite HTTP/REST library.  We have a testing environment referred to \"sandbox\", which you can setup to test API calls without affecting production data. Currently, our sandbox environment is live while our production environment is under development and will be available soon. You can sign up on our Dashboard to get API keys to access Hyperswitch API.  ### Environment  Use the following base URLs when making requests to the APIs:  | Environment   |  Base URL                          | |---------------|------------------------------------| | Sandbox       | <https://sandbox.hyperswitch.io>   | | Production    | <https://api.hyperswitch.io>       |  ## Authentication  When you sign up on our [dashboard](https://app.hyperswitch.io) and create a merchant account, you are given a secret key (also referred as api-key) and a publishable key. You may authenticate all API requests with Hyperswitch server by providing the appropriate key in the request Authorization header.  | Key             |  Description                                                                                  | |-----------------|-----------------------------------------------------------------------------------------------| | api-key         | Private key. Used to authenticate all API requests from your merchant server                  | | publishable key | Unique identifier for your account. Used to authenticate API requests from your app's client  |  Never share your secret api keys. Keep them guarded and secure. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hyperswitch@juspay.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.hyperswitch.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.util.StringJoiner;

/**
* BacsBankTransferInstructions
*/
    @JsonPropertyOrder({
        BacsBankTransferInstructions.JSON_PROPERTY_ACCOUNT_HOLDER_NAME,
        BacsBankTransferInstructions.JSON_PROPERTY_ACCOUNT_NUMBER,
        BacsBankTransferInstructions.JSON_PROPERTY_SORT_CODE
    })
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.11.0")
public class BacsBankTransferInstructions {
        public static final String JSON_PROPERTY_ACCOUNT_HOLDER_NAME = "account_holder_name";
    @javax.annotation.Nonnull
            private String accountHolderName;

        public static final String JSON_PROPERTY_ACCOUNT_NUMBER = "account_number";
    @javax.annotation.Nonnull
            private String accountNumber;

        public static final String JSON_PROPERTY_SORT_CODE = "sort_code";
    @javax.annotation.Nonnull
            private String sortCode;

public BacsBankTransferInstructions() {
}

        public BacsBankTransferInstructions accountHolderName(@javax.annotation.Nonnull String accountHolderName) {
        
        this.accountHolderName = accountHolderName;
        return this;
        }

    /**
        * Get accountHolderName
    * @return accountHolderName
    */
    @javax.annotation.Nonnull
      @JsonProperty(JSON_PROPERTY_ACCOUNT_HOLDER_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

    public String getAccountHolderName() {
        return accountHolderName;
    }


          @JsonProperty(JSON_PROPERTY_ACCOUNT_HOLDER_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAccountHolderName(@javax.annotation.Nonnull String accountHolderName) {
            this.accountHolderName = accountHolderName;
        }

        public BacsBankTransferInstructions accountNumber(@javax.annotation.Nonnull String accountNumber) {
        
        this.accountNumber = accountNumber;
        return this;
        }

    /**
        * Get accountNumber
    * @return accountNumber
    */
    @javax.annotation.Nonnull
      @JsonProperty(JSON_PROPERTY_ACCOUNT_NUMBER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

    public String getAccountNumber() {
        return accountNumber;
    }


          @JsonProperty(JSON_PROPERTY_ACCOUNT_NUMBER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAccountNumber(@javax.annotation.Nonnull String accountNumber) {
            this.accountNumber = accountNumber;
        }

        public BacsBankTransferInstructions sortCode(@javax.annotation.Nonnull String sortCode) {
        
        this.sortCode = sortCode;
        return this;
        }

    /**
        * Get sortCode
    * @return sortCode
    */
    @javax.annotation.Nonnull
      @JsonProperty(JSON_PROPERTY_SORT_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

    public String getSortCode() {
        return sortCode;
    }


          @JsonProperty(JSON_PROPERTY_SORT_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSortCode(@javax.annotation.Nonnull String sortCode) {
            this.sortCode = sortCode;
        }

@Override
public boolean equals(Object o) {
    if (this == o) {
    return true;
    }
    if (o == null || getClass() != o.getClass()) {
    return false;
    }
        BacsBankTransferInstructions bacsBankTransferInstructions = (BacsBankTransferInstructions) o;
        return Objects.equals(this.accountHolderName, bacsBankTransferInstructions.accountHolderName) &&
        Objects.equals(this.accountNumber, bacsBankTransferInstructions.accountNumber) &&
        Objects.equals(this.sortCode, bacsBankTransferInstructions.sortCode);
}

    @Override
    public int hashCode() {
        return Objects.hash(accountHolderName, accountNumber, sortCode);
    }

    @Override
    public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BacsBankTransferInstructions {\n");
        sb.append("    accountHolderName: ").append(toIndentedString(accountHolderName)).append("\n");
        sb.append("    accountNumber: ").append(toIndentedString(accountNumber)).append("\n");
        sb.append("    sortCode: ").append(toIndentedString(sortCode)).append("\n");
    sb.append("}");
    return sb.toString();
    }

    /**
    * Convert the given object to string with each line indented by 4 spaces
    * (except the first line).
    */
    private String toIndentedString(Object o) {
    if (o == null) {
    return "null";
    }
    return o.toString().replace("\n", "\n    ");
    }

        /**
        * Convert the instance into URL query string.
        *
        * @return URL query string
        */
        public String toUrlQueryString() {
        return toUrlQueryString(null);
        }

        /**
        * Convert the instance into URL query string.
        *
        * @param prefix prefix of the query string
        * @return URL query string
        */
        public String toUrlQueryString(String prefix) {
        String suffix = "";
        String containerSuffix = "";
        String containerPrefix = "";
        if (prefix == null) {
        // style=form, explode=true, e.g. /pet?name=cat&type=manx
        prefix = "";
        } else {
        // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
        prefix = prefix + "[";
        suffix = "]";
        containerSuffix = "]";
        containerPrefix = "[";
        }

        StringJoiner joiner = new StringJoiner("&");

            // add `account_holder_name` to the URL query string
                        if (getAccountHolderName() != null) {
                        try {
                        joiner.add(String.format("%saccount_holder_name%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getAccountHolderName()), "UTF-8").replaceAll("\\+", "%20")));
                        } catch (UnsupportedEncodingException e) {
                        // Should never happen, UTF-8 is always supported
                        throw new RuntimeException(e);
                        }
                        }

            // add `account_number` to the URL query string
                        if (getAccountNumber() != null) {
                        try {
                        joiner.add(String.format("%saccount_number%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getAccountNumber()), "UTF-8").replaceAll("\\+", "%20")));
                        } catch (UnsupportedEncodingException e) {
                        // Should never happen, UTF-8 is always supported
                        throw new RuntimeException(e);
                        }
                        }

            // add `sort_code` to the URL query string
                        if (getSortCode() != null) {
                        try {
                        joiner.add(String.format("%ssort_code%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getSortCode()), "UTF-8").replaceAll("\\+", "%20")));
                        } catch (UnsupportedEncodingException e) {
                        // Should never happen, UTF-8 is always supported
                        throw new RuntimeException(e);
                        }
                        }

        return joiner.toString();
        }

    }

