/*
 * Hyperswitch - API Documentation
 *  ## Get started  Hyperswitch provides a collection of APIs that enable you to process and manage payments. Our APIs accept and return JSON in the HTTP body, and return standard HTTP response codes.  You can consume the APIs directly using your favorite HTTP/REST library.  We have a testing environment referred to \"sandbox\", which you can setup to test API calls without affecting production data. Currently, our sandbox environment is live while our production environment is under development and will be available soon. You can sign up on our Dashboard to get API keys to access Hyperswitch API.  ### Environment  Use the following base URLs when making requests to the APIs:  | Environment   |  Base URL                          | |---------------|------------------------------------| | Sandbox       | <https://sandbox.hyperswitch.io>   | | Production    | <https://api.hyperswitch.io>       |  ## Authentication  When you sign up on our [dashboard](https://app.hyperswitch.io) and create a merchant account, you are given a secret key (also referred as api-key) and a publishable key. You may authenticate all API requests with Hyperswitch server by providing the appropriate key in the request Authorization header.  | Key             |  Description                                                                                  | |-----------------|-----------------------------------------------------------------------------------------------| | api-key         | Private key. Used to authenticate all API requests from your merchant server                  | | publishable key | Unique identifier for your account. Used to authenticate API requests from your app's client  |  Never share your secret api keys. Keep them guarded and secure. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hyperswitch@juspay.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.hyperswitch.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.hyperswitch.client.model.ApplepayInitiative;
import com.hyperswitch.client.model.CountryAlpha2;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.util.StringJoiner;

/**
 * SessionTokenInfo
 */
@JsonPropertyOrder({
  SessionTokenInfo.JSON_PROPERTY_PAYMENT_PROCESSING_CERTIFICATE,
  SessionTokenInfo.JSON_PROPERTY_PAYMENT_PROCESSING_CERTIFICATE_KEY,
  SessionTokenInfo.JSON_PROPERTY_PAYMENT_PROCESSING_DETAILS_AT,
  SessionTokenInfo.JSON_PROPERTY_CERTIFICATE,
  SessionTokenInfo.JSON_PROPERTY_CERTIFICATE_KEYS,
  SessionTokenInfo.JSON_PROPERTY_MERCHANT_IDENTIFIER,
  SessionTokenInfo.JSON_PROPERTY_DISPLAY_NAME,
  SessionTokenInfo.JSON_PROPERTY_INITIATIVE,
  SessionTokenInfo.JSON_PROPERTY_INITIATIVE_CONTEXT,
  SessionTokenInfo.JSON_PROPERTY_MERCHANT_BUSINESS_COUNTRY
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.11.0")
@JsonIgnoreProperties(
  value = "payment_processing_details_at", // ignore manually set payment_processing_details_at, it will be automatically generated by Jackson during serialization
  allowSetters = true // allows the payment_processing_details_at to be set during deserialization
)
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "payment_processing_details_at", visible = true)

public class SessionTokenInfo {
  public static final String JSON_PROPERTY_PAYMENT_PROCESSING_CERTIFICATE = "payment_processing_certificate";
  @javax.annotation.Nonnull
  private String paymentProcessingCertificate;

  public static final String JSON_PROPERTY_PAYMENT_PROCESSING_CERTIFICATE_KEY = "payment_processing_certificate_key";
  @javax.annotation.Nonnull
  private String paymentProcessingCertificateKey;

  /**
   * Gets or Sets paymentProcessingDetailsAt
   */
  public enum PaymentProcessingDetailsAtEnum {
    CONNECTOR(String.valueOf("Connector"));

    private String value;

    PaymentProcessingDetailsAtEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static PaymentProcessingDetailsAtEnum fromValue(String value) {
      for (PaymentProcessingDetailsAtEnum b : PaymentProcessingDetailsAtEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_PAYMENT_PROCESSING_DETAILS_AT = "payment_processing_details_at";
  @javax.annotation.Nonnull
  private PaymentProcessingDetailsAtEnum paymentProcessingDetailsAt;

  public static final String JSON_PROPERTY_CERTIFICATE = "certificate";
  @javax.annotation.Nonnull
  private String certificate;

  public static final String JSON_PROPERTY_CERTIFICATE_KEYS = "certificate_keys";
  @javax.annotation.Nonnull
  private String certificateKeys;

  public static final String JSON_PROPERTY_MERCHANT_IDENTIFIER = "merchant_identifier";
  @javax.annotation.Nonnull
  private String merchantIdentifier;

  public static final String JSON_PROPERTY_DISPLAY_NAME = "display_name";
  @javax.annotation.Nonnull
  private String displayName;

  public static final String JSON_PROPERTY_INITIATIVE = "initiative";
  @javax.annotation.Nonnull
  private ApplepayInitiative initiative;

  public static final String JSON_PROPERTY_INITIATIVE_CONTEXT = "initiative_context";
  @javax.annotation.Nullable
  private JsonNullable<String> initiativeContext = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_MERCHANT_BUSINESS_COUNTRY = "merchant_business_country";
  @javax.annotation.Nullable
  private JsonNullable<CountryAlpha2> merchantBusinessCountry = JsonNullable.<CountryAlpha2>undefined();

  public SessionTokenInfo() {
  }

  public SessionTokenInfo paymentProcessingCertificate(@javax.annotation.Nonnull String paymentProcessingCertificate) {
    
    this.paymentProcessingCertificate = paymentProcessingCertificate;
    return this;
  }

  /**
   * Get paymentProcessingCertificate
   * @return paymentProcessingCertificate
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_PAYMENT_PROCESSING_CERTIFICATE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getPaymentProcessingCertificate() {
    return paymentProcessingCertificate;
  }


  @JsonProperty(JSON_PROPERTY_PAYMENT_PROCESSING_CERTIFICATE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPaymentProcessingCertificate(@javax.annotation.Nonnull String paymentProcessingCertificate) {
    this.paymentProcessingCertificate = paymentProcessingCertificate;
  }

  public SessionTokenInfo paymentProcessingCertificateKey(@javax.annotation.Nonnull String paymentProcessingCertificateKey) {
    
    this.paymentProcessingCertificateKey = paymentProcessingCertificateKey;
    return this;
  }

  /**
   * Get paymentProcessingCertificateKey
   * @return paymentProcessingCertificateKey
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_PAYMENT_PROCESSING_CERTIFICATE_KEY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getPaymentProcessingCertificateKey() {
    return paymentProcessingCertificateKey;
  }


  @JsonProperty(JSON_PROPERTY_PAYMENT_PROCESSING_CERTIFICATE_KEY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPaymentProcessingCertificateKey(@javax.annotation.Nonnull String paymentProcessingCertificateKey) {
    this.paymentProcessingCertificateKey = paymentProcessingCertificateKey;
  }

  public SessionTokenInfo paymentProcessingDetailsAt(@javax.annotation.Nonnull PaymentProcessingDetailsAtEnum paymentProcessingDetailsAt) {
    
    this.paymentProcessingDetailsAt = paymentProcessingDetailsAt;
    return this;
  }

  /**
   * Get paymentProcessingDetailsAt
   * @return paymentProcessingDetailsAt
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_PAYMENT_PROCESSING_DETAILS_AT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public PaymentProcessingDetailsAtEnum getPaymentProcessingDetailsAt() {
    return paymentProcessingDetailsAt;
  }


  @JsonProperty(JSON_PROPERTY_PAYMENT_PROCESSING_DETAILS_AT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPaymentProcessingDetailsAt(@javax.annotation.Nonnull PaymentProcessingDetailsAtEnum paymentProcessingDetailsAt) {
    this.paymentProcessingDetailsAt = paymentProcessingDetailsAt;
  }

  public SessionTokenInfo certificate(@javax.annotation.Nonnull String certificate) {
    
    this.certificate = certificate;
    return this;
  }

  /**
   * Get certificate
   * @return certificate
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CERTIFICATE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getCertificate() {
    return certificate;
  }


  @JsonProperty(JSON_PROPERTY_CERTIFICATE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCertificate(@javax.annotation.Nonnull String certificate) {
    this.certificate = certificate;
  }

  public SessionTokenInfo certificateKeys(@javax.annotation.Nonnull String certificateKeys) {
    
    this.certificateKeys = certificateKeys;
    return this;
  }

  /**
   * Get certificateKeys
   * @return certificateKeys
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CERTIFICATE_KEYS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getCertificateKeys() {
    return certificateKeys;
  }


  @JsonProperty(JSON_PROPERTY_CERTIFICATE_KEYS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCertificateKeys(@javax.annotation.Nonnull String certificateKeys) {
    this.certificateKeys = certificateKeys;
  }

  public SessionTokenInfo merchantIdentifier(@javax.annotation.Nonnull String merchantIdentifier) {
    
    this.merchantIdentifier = merchantIdentifier;
    return this;
  }

  /**
   * Get merchantIdentifier
   * @return merchantIdentifier
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_MERCHANT_IDENTIFIER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getMerchantIdentifier() {
    return merchantIdentifier;
  }


  @JsonProperty(JSON_PROPERTY_MERCHANT_IDENTIFIER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMerchantIdentifier(@javax.annotation.Nonnull String merchantIdentifier) {
    this.merchantIdentifier = merchantIdentifier;
  }

  public SessionTokenInfo displayName(@javax.annotation.Nonnull String displayName) {
    
    this.displayName = displayName;
    return this;
  }

  /**
   * Get displayName
   * @return displayName
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_DISPLAY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getDisplayName() {
    return displayName;
  }


  @JsonProperty(JSON_PROPERTY_DISPLAY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDisplayName(@javax.annotation.Nonnull String displayName) {
    this.displayName = displayName;
  }

  public SessionTokenInfo initiative(@javax.annotation.Nonnull ApplepayInitiative initiative) {
    
    this.initiative = initiative;
    return this;
  }

  /**
   * Get initiative
   * @return initiative
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_INITIATIVE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public ApplepayInitiative getInitiative() {
    return initiative;
  }


  @JsonProperty(JSON_PROPERTY_INITIATIVE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setInitiative(@javax.annotation.Nonnull ApplepayInitiative initiative) {
    this.initiative = initiative;
  }

  public SessionTokenInfo initiativeContext(@javax.annotation.Nullable String initiativeContext) {
    this.initiativeContext = JsonNullable.<String>of(initiativeContext);
    
    return this;
  }

  /**
   * Get initiativeContext
   * @return initiativeContext
   */
  @javax.annotation.Nullable
  @JsonIgnore

  public String getInitiativeContext() {
        return initiativeContext.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_INITIATIVE_CONTEXT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getInitiativeContext_JsonNullable() {
    return initiativeContext;
  }
  
  @JsonProperty(JSON_PROPERTY_INITIATIVE_CONTEXT)
  public void setInitiativeContext_JsonNullable(JsonNullable<String> initiativeContext) {
    this.initiativeContext = initiativeContext;
  }

  public void setInitiativeContext(@javax.annotation.Nullable String initiativeContext) {
    this.initiativeContext = JsonNullable.<String>of(initiativeContext);
  }

  public SessionTokenInfo merchantBusinessCountry(@javax.annotation.Nullable CountryAlpha2 merchantBusinessCountry) {
    this.merchantBusinessCountry = JsonNullable.<CountryAlpha2>of(merchantBusinessCountry);
    
    return this;
  }

  /**
   * Get merchantBusinessCountry
   * @return merchantBusinessCountry
   */
  @javax.annotation.Nullable
  @JsonIgnore

  public CountryAlpha2 getMerchantBusinessCountry() {
        return merchantBusinessCountry.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_MERCHANT_BUSINESS_COUNTRY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<CountryAlpha2> getMerchantBusinessCountry_JsonNullable() {
    return merchantBusinessCountry;
  }
  
  @JsonProperty(JSON_PROPERTY_MERCHANT_BUSINESS_COUNTRY)
  public void setMerchantBusinessCountry_JsonNullable(JsonNullable<CountryAlpha2> merchantBusinessCountry) {
    this.merchantBusinessCountry = merchantBusinessCountry;
  }

  public void setMerchantBusinessCountry(@javax.annotation.Nullable CountryAlpha2 merchantBusinessCountry) {
    this.merchantBusinessCountry = JsonNullable.<CountryAlpha2>of(merchantBusinessCountry);
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SessionTokenInfo sessionTokenInfo = (SessionTokenInfo) o;
    return Objects.equals(this.paymentProcessingCertificate, sessionTokenInfo.paymentProcessingCertificate) &&
        Objects.equals(this.paymentProcessingCertificateKey, sessionTokenInfo.paymentProcessingCertificateKey) &&
        Objects.equals(this.paymentProcessingDetailsAt, sessionTokenInfo.paymentProcessingDetailsAt) &&
        Objects.equals(this.certificate, sessionTokenInfo.certificate) &&
        Objects.equals(this.certificateKeys, sessionTokenInfo.certificateKeys) &&
        Objects.equals(this.merchantIdentifier, sessionTokenInfo.merchantIdentifier) &&
        Objects.equals(this.displayName, sessionTokenInfo.displayName) &&
        Objects.equals(this.initiative, sessionTokenInfo.initiative) &&
        equalsNullable(this.initiativeContext, sessionTokenInfo.initiativeContext) &&
        equalsNullable(this.merchantBusinessCountry, sessionTokenInfo.merchantBusinessCountry);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(paymentProcessingCertificate, paymentProcessingCertificateKey, paymentProcessingDetailsAt, certificate, certificateKeys, merchantIdentifier, displayName, initiative, hashCodeNullable(initiativeContext), hashCodeNullable(merchantBusinessCountry));
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SessionTokenInfo {\n");
    sb.append("    paymentProcessingCertificate: ").append(toIndentedString(paymentProcessingCertificate)).append("\n");
    sb.append("    paymentProcessingCertificateKey: ").append(toIndentedString(paymentProcessingCertificateKey)).append("\n");
    sb.append("    paymentProcessingDetailsAt: ").append(toIndentedString(paymentProcessingDetailsAt)).append("\n");
    sb.append("    certificate: ").append(toIndentedString(certificate)).append("\n");
    sb.append("    certificateKeys: ").append(toIndentedString(certificateKeys)).append("\n");
    sb.append("    merchantIdentifier: ").append(toIndentedString(merchantIdentifier)).append("\n");
    sb.append("    displayName: ").append(toIndentedString(displayName)).append("\n");
    sb.append("    initiative: ").append(toIndentedString(initiative)).append("\n");
    sb.append("    initiativeContext: ").append(toIndentedString(initiativeContext)).append("\n");
    sb.append("    merchantBusinessCountry: ").append(toIndentedString(merchantBusinessCountry)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `payment_processing_certificate` to the URL query string
    if (getPaymentProcessingCertificate() != null) {
      try {
        joiner.add(String.format("%spayment_processing_certificate%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getPaymentProcessingCertificate()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `payment_processing_certificate_key` to the URL query string
    if (getPaymentProcessingCertificateKey() != null) {
      try {
        joiner.add(String.format("%spayment_processing_certificate_key%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getPaymentProcessingCertificateKey()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `payment_processing_details_at` to the URL query string
    if (getPaymentProcessingDetailsAt() != null) {
      try {
        joiner.add(String.format("%spayment_processing_details_at%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getPaymentProcessingDetailsAt()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `certificate` to the URL query string
    if (getCertificate() != null) {
      try {
        joiner.add(String.format("%scertificate%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getCertificate()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `certificate_keys` to the URL query string
    if (getCertificateKeys() != null) {
      try {
        joiner.add(String.format("%scertificate_keys%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getCertificateKeys()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `merchant_identifier` to the URL query string
    if (getMerchantIdentifier() != null) {
      try {
        joiner.add(String.format("%smerchant_identifier%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getMerchantIdentifier()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `display_name` to the URL query string
    if (getDisplayName() != null) {
      try {
        joiner.add(String.format("%sdisplay_name%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getDisplayName()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `initiative` to the URL query string
    if (getInitiative() != null) {
      try {
        joiner.add(String.format("%sinitiative%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getInitiative()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `initiative_context` to the URL query string
    if (getInitiativeContext() != null) {
      try {
        joiner.add(String.format("%sinitiative_context%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getInitiativeContext()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `merchant_business_country` to the URL query string
    if (getMerchantBusinessCountry() != null) {
      try {
        joiner.add(String.format("%smerchant_business_country%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getMerchantBusinessCountry()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    return joiner.toString();
  }

}

