/*
 * Hyperswitch - API Documentation
 *  ## Get started  Hyperswitch provides a collection of APIs that enable you to process and manage payments. Our APIs accept and return JSON in the HTTP body, and return standard HTTP response codes.  You can consume the APIs directly using your favorite HTTP/REST library.  We have a testing environment referred to \"sandbox\", which you can setup to test API calls without affecting production data. Currently, our sandbox environment is live while our production environment is under development and will be available soon. You can sign up on our Dashboard to get API keys to access Hyperswitch API.  ### Environment  Use the following base URLs when making requests to the APIs:  | Environment   |  Base URL                          | |---------------|------------------------------------| | Sandbox       | <https://sandbox.hyperswitch.io>   | | Production    | <https://api.hyperswitch.io>       |  ## Authentication  When you sign up on our [dashboard](https://app.hyperswitch.io) and create a merchant account, you are given a secret key (also referred as api-key) and a publishable key. You may authenticate all API requests with Hyperswitch server by providing the appropriate key in the request Authorization header.  | Key             |  Description                                                                                  | |-----------------|-----------------------------------------------------------------------------------------------| | api-key         | Private key. Used to authenticate all API requests from your merchant server                  | | publishable key | Unique identifier for your account. Used to authenticate API requests from your app's client  |  Never share your secret api keys. Keep them guarded and secure. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hyperswitch@juspay.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.lumeweb.hyperswitch.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.lumeweb.hyperswitch.model.PayLaterDataOneOf;
import com.lumeweb.hyperswitch.model.PayLaterDataOneOf1;
import com.lumeweb.hyperswitch.model.PayLaterDataOneOf1KlarnaSdk;
import com.lumeweb.hyperswitch.model.PayLaterDataOneOf2;
import com.lumeweb.hyperswitch.model.PayLaterDataOneOf3;
import com.lumeweb.hyperswitch.model.PayLaterDataOneOf3AfterpayClearpayRedirect;
import com.lumeweb.hyperswitch.model.PayLaterDataOneOf4;
import com.lumeweb.hyperswitch.model.PayLaterDataOneOf5;
import com.lumeweb.hyperswitch.model.PayLaterDataOneOf6;
import com.lumeweb.hyperswitch.model.PayLaterDataOneOf7;
import com.lumeweb.hyperswitch.model.PayLaterDataOneOfKlarnaRedirect;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import com.fasterxml.jackson.core.type.TypeReference;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;

import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.JsonToken;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonMappingException;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.MapperFeature;
import com.fasterxml.jackson.databind.SerializerProvider;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;
import com.fasterxml.jackson.databind.ser.std.StdSerializer;
import com.lumeweb.hyperswitch.client.JSON;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.11.0-SNAPSHOT")
@JsonDeserialize(using = PayLaterData.PayLaterDataDeserializer.class)
@JsonSerialize(using = PayLaterData.PayLaterDataSerializer.class)
public class PayLaterData extends AbstractOpenApiSchema {
    private static final Logger log = Logger.getLogger(PayLaterData.class.getName());

    public static class PayLaterDataSerializer extends StdSerializer<PayLaterData> {
        public PayLaterDataSerializer(Class<PayLaterData> t) {
            super(t);
        }

        public PayLaterDataSerializer() {
            this(null);
        }

        @Override
        public void serialize(PayLaterData value, JsonGenerator jgen, SerializerProvider provider) throws IOException, JsonProcessingException {
            jgen.writeObject(value.getActualInstance());
        }
    }

    public static class PayLaterDataDeserializer extends StdDeserializer<PayLaterData> {
        public PayLaterDataDeserializer() {
            this(PayLaterData.class);
        }

        public PayLaterDataDeserializer(Class<?> vc) {
            super(vc);
        }

        @Override
        public PayLaterData deserialize(JsonParser jp, DeserializationContext ctxt) throws IOException, JsonProcessingException {
            JsonNode tree = jp.readValueAsTree();
            Object deserialized = null;
            boolean typeCoercion = ctxt.isEnabled(MapperFeature.ALLOW_COERCION_OF_SCALARS);
            int match = 0;
            JsonToken token = tree.traverse(jp.getCodec()).nextToken();
            // deserialize PayLaterDataOneOf
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (PayLaterDataOneOf.class.equals(Integer.class) || PayLaterDataOneOf.class.equals(Long.class) || PayLaterDataOneOf.class.equals(Float.class) || PayLaterDataOneOf.class.equals(Double.class) || PayLaterDataOneOf.class.equals(Boolean.class) || PayLaterDataOneOf.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((PayLaterDataOneOf.class.equals(Integer.class) || PayLaterDataOneOf.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((PayLaterDataOneOf.class.equals(Float.class) || PayLaterDataOneOf.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (PayLaterDataOneOf.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (PayLaterDataOneOf.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(PayLaterDataOneOf.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'PayLaterDataOneOf'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'PayLaterDataOneOf'", e);
            }

            // deserialize PayLaterDataOneOf1
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (PayLaterDataOneOf1.class.equals(Integer.class) || PayLaterDataOneOf1.class.equals(Long.class) || PayLaterDataOneOf1.class.equals(Float.class) || PayLaterDataOneOf1.class.equals(Double.class) || PayLaterDataOneOf1.class.equals(Boolean.class) || PayLaterDataOneOf1.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((PayLaterDataOneOf1.class.equals(Integer.class) || PayLaterDataOneOf1.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((PayLaterDataOneOf1.class.equals(Float.class) || PayLaterDataOneOf1.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (PayLaterDataOneOf1.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (PayLaterDataOneOf1.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(PayLaterDataOneOf1.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'PayLaterDataOneOf1'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'PayLaterDataOneOf1'", e);
            }

            // deserialize PayLaterDataOneOf2
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (PayLaterDataOneOf2.class.equals(Integer.class) || PayLaterDataOneOf2.class.equals(Long.class) || PayLaterDataOneOf2.class.equals(Float.class) || PayLaterDataOneOf2.class.equals(Double.class) || PayLaterDataOneOf2.class.equals(Boolean.class) || PayLaterDataOneOf2.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((PayLaterDataOneOf2.class.equals(Integer.class) || PayLaterDataOneOf2.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((PayLaterDataOneOf2.class.equals(Float.class) || PayLaterDataOneOf2.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (PayLaterDataOneOf2.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (PayLaterDataOneOf2.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(PayLaterDataOneOf2.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'PayLaterDataOneOf2'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'PayLaterDataOneOf2'", e);
            }

            // deserialize PayLaterDataOneOf3
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (PayLaterDataOneOf3.class.equals(Integer.class) || PayLaterDataOneOf3.class.equals(Long.class) || PayLaterDataOneOf3.class.equals(Float.class) || PayLaterDataOneOf3.class.equals(Double.class) || PayLaterDataOneOf3.class.equals(Boolean.class) || PayLaterDataOneOf3.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((PayLaterDataOneOf3.class.equals(Integer.class) || PayLaterDataOneOf3.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((PayLaterDataOneOf3.class.equals(Float.class) || PayLaterDataOneOf3.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (PayLaterDataOneOf3.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (PayLaterDataOneOf3.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(PayLaterDataOneOf3.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'PayLaterDataOneOf3'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'PayLaterDataOneOf3'", e);
            }

            // deserialize PayLaterDataOneOf4
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (PayLaterDataOneOf4.class.equals(Integer.class) || PayLaterDataOneOf4.class.equals(Long.class) || PayLaterDataOneOf4.class.equals(Float.class) || PayLaterDataOneOf4.class.equals(Double.class) || PayLaterDataOneOf4.class.equals(Boolean.class) || PayLaterDataOneOf4.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((PayLaterDataOneOf4.class.equals(Integer.class) || PayLaterDataOneOf4.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((PayLaterDataOneOf4.class.equals(Float.class) || PayLaterDataOneOf4.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (PayLaterDataOneOf4.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (PayLaterDataOneOf4.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(PayLaterDataOneOf4.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'PayLaterDataOneOf4'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'PayLaterDataOneOf4'", e);
            }

            // deserialize PayLaterDataOneOf5
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (PayLaterDataOneOf5.class.equals(Integer.class) || PayLaterDataOneOf5.class.equals(Long.class) || PayLaterDataOneOf5.class.equals(Float.class) || PayLaterDataOneOf5.class.equals(Double.class) || PayLaterDataOneOf5.class.equals(Boolean.class) || PayLaterDataOneOf5.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((PayLaterDataOneOf5.class.equals(Integer.class) || PayLaterDataOneOf5.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((PayLaterDataOneOf5.class.equals(Float.class) || PayLaterDataOneOf5.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (PayLaterDataOneOf5.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (PayLaterDataOneOf5.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(PayLaterDataOneOf5.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'PayLaterDataOneOf5'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'PayLaterDataOneOf5'", e);
            }

            // deserialize PayLaterDataOneOf6
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (PayLaterDataOneOf6.class.equals(Integer.class) || PayLaterDataOneOf6.class.equals(Long.class) || PayLaterDataOneOf6.class.equals(Float.class) || PayLaterDataOneOf6.class.equals(Double.class) || PayLaterDataOneOf6.class.equals(Boolean.class) || PayLaterDataOneOf6.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((PayLaterDataOneOf6.class.equals(Integer.class) || PayLaterDataOneOf6.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((PayLaterDataOneOf6.class.equals(Float.class) || PayLaterDataOneOf6.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (PayLaterDataOneOf6.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (PayLaterDataOneOf6.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(PayLaterDataOneOf6.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'PayLaterDataOneOf6'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'PayLaterDataOneOf6'", e);
            }

            // deserialize PayLaterDataOneOf7
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (PayLaterDataOneOf7.class.equals(Integer.class) || PayLaterDataOneOf7.class.equals(Long.class) || PayLaterDataOneOf7.class.equals(Float.class) || PayLaterDataOneOf7.class.equals(Double.class) || PayLaterDataOneOf7.class.equals(Boolean.class) || PayLaterDataOneOf7.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((PayLaterDataOneOf7.class.equals(Integer.class) || PayLaterDataOneOf7.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((PayLaterDataOneOf7.class.equals(Float.class) || PayLaterDataOneOf7.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (PayLaterDataOneOf7.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (PayLaterDataOneOf7.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(PayLaterDataOneOf7.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'PayLaterDataOneOf7'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'PayLaterDataOneOf7'", e);
            }

            if (match == 1) {
                PayLaterData ret = new PayLaterData();
                ret.setActualInstance(deserialized);
                return ret;
            }
            throw new IOException(String.format("Failed deserialization for PayLaterData: %d classes match result, expected 1", match));
        }

        /**
         * Handle deserialization of the 'null' value.
         */
        @Override
        public PayLaterData getNullValue(DeserializationContext ctxt) throws JsonMappingException {
            throw new JsonMappingException(ctxt.getParser(), "PayLaterData cannot be null");
        }
    }

    // store a list of schema names defined in oneOf
    public static final Map<String, Class<?>> schemas = new HashMap<>();

    public PayLaterData() {
        super("oneOf", Boolean.FALSE);
    }

    public PayLaterData(PayLaterDataOneOf o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public PayLaterData(PayLaterDataOneOf1 o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public PayLaterData(PayLaterDataOneOf2 o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public PayLaterData(PayLaterDataOneOf3 o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public PayLaterData(PayLaterDataOneOf4 o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public PayLaterData(PayLaterDataOneOf5 o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public PayLaterData(PayLaterDataOneOf6 o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public PayLaterData(PayLaterDataOneOf7 o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    static {
        schemas.put("PayLaterDataOneOf", PayLaterDataOneOf.class);
        schemas.put("PayLaterDataOneOf1", PayLaterDataOneOf1.class);
        schemas.put("PayLaterDataOneOf2", PayLaterDataOneOf2.class);
        schemas.put("PayLaterDataOneOf3", PayLaterDataOneOf3.class);
        schemas.put("PayLaterDataOneOf4", PayLaterDataOneOf4.class);
        schemas.put("PayLaterDataOneOf5", PayLaterDataOneOf5.class);
        schemas.put("PayLaterDataOneOf6", PayLaterDataOneOf6.class);
        schemas.put("PayLaterDataOneOf7", PayLaterDataOneOf7.class);
        JSON.registerDescendants(PayLaterData.class, Collections.unmodifiableMap(schemas));
    }

    @Override
    public Map<String, Class<?>> getSchemas() {
        return PayLaterData.schemas;
    }

    /**
     * Set the instance that matches the oneOf child schema, check
     * the instance parameter is valid against the oneOf child schemas:
     * PayLaterDataOneOf, PayLaterDataOneOf1, PayLaterDataOneOf2, PayLaterDataOneOf3, PayLaterDataOneOf4, PayLaterDataOneOf5, PayLaterDataOneOf6, PayLaterDataOneOf7
     *
     * It could be an instance of the 'oneOf' schemas.
     * The oneOf child schemas may themselves be a composed schema (allOf, anyOf, oneOf).
     */
    @Override
    public void setActualInstance(Object instance) {
        if (JSON.isInstanceOf(PayLaterDataOneOf.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(PayLaterDataOneOf1.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(PayLaterDataOneOf2.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(PayLaterDataOneOf3.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(PayLaterDataOneOf4.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(PayLaterDataOneOf5.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(PayLaterDataOneOf6.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(PayLaterDataOneOf7.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        throw new RuntimeException("Invalid instance type. Must be PayLaterDataOneOf, PayLaterDataOneOf1, PayLaterDataOneOf2, PayLaterDataOneOf3, PayLaterDataOneOf4, PayLaterDataOneOf5, PayLaterDataOneOf6, PayLaterDataOneOf7");
    }

    /**
     * Get the actual instance, which can be the following:
     * PayLaterDataOneOf, PayLaterDataOneOf1, PayLaterDataOneOf2, PayLaterDataOneOf3, PayLaterDataOneOf4, PayLaterDataOneOf5, PayLaterDataOneOf6, PayLaterDataOneOf7
     *
     * @return The actual instance (PayLaterDataOneOf, PayLaterDataOneOf1, PayLaterDataOneOf2, PayLaterDataOneOf3, PayLaterDataOneOf4, PayLaterDataOneOf5, PayLaterDataOneOf6, PayLaterDataOneOf7)
     */
    @Override
    public Object getActualInstance() {
        return super.getActualInstance();
    }

    /**
     * Get the actual instance of `PayLaterDataOneOf`. If the actual instance is not `PayLaterDataOneOf`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `PayLaterDataOneOf`
     * @throws ClassCastException if the instance is not `PayLaterDataOneOf`
     */
    public PayLaterDataOneOf getPayLaterDataOneOf() throws ClassCastException {
        return (PayLaterDataOneOf)super.getActualInstance();
    }

    /**
     * Get the actual instance of `PayLaterDataOneOf1`. If the actual instance is not `PayLaterDataOneOf1`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `PayLaterDataOneOf1`
     * @throws ClassCastException if the instance is not `PayLaterDataOneOf1`
     */
    public PayLaterDataOneOf1 getPayLaterDataOneOf1() throws ClassCastException {
        return (PayLaterDataOneOf1)super.getActualInstance();
    }

    /**
     * Get the actual instance of `PayLaterDataOneOf2`. If the actual instance is not `PayLaterDataOneOf2`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `PayLaterDataOneOf2`
     * @throws ClassCastException if the instance is not `PayLaterDataOneOf2`
     */
    public PayLaterDataOneOf2 getPayLaterDataOneOf2() throws ClassCastException {
        return (PayLaterDataOneOf2)super.getActualInstance();
    }

    /**
     * Get the actual instance of `PayLaterDataOneOf3`. If the actual instance is not `PayLaterDataOneOf3`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `PayLaterDataOneOf3`
     * @throws ClassCastException if the instance is not `PayLaterDataOneOf3`
     */
    public PayLaterDataOneOf3 getPayLaterDataOneOf3() throws ClassCastException {
        return (PayLaterDataOneOf3)super.getActualInstance();
    }

    /**
     * Get the actual instance of `PayLaterDataOneOf4`. If the actual instance is not `PayLaterDataOneOf4`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `PayLaterDataOneOf4`
     * @throws ClassCastException if the instance is not `PayLaterDataOneOf4`
     */
    public PayLaterDataOneOf4 getPayLaterDataOneOf4() throws ClassCastException {
        return (PayLaterDataOneOf4)super.getActualInstance();
    }

    /**
     * Get the actual instance of `PayLaterDataOneOf5`. If the actual instance is not `PayLaterDataOneOf5`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `PayLaterDataOneOf5`
     * @throws ClassCastException if the instance is not `PayLaterDataOneOf5`
     */
    public PayLaterDataOneOf5 getPayLaterDataOneOf5() throws ClassCastException {
        return (PayLaterDataOneOf5)super.getActualInstance();
    }

    /**
     * Get the actual instance of `PayLaterDataOneOf6`. If the actual instance is not `PayLaterDataOneOf6`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `PayLaterDataOneOf6`
     * @throws ClassCastException if the instance is not `PayLaterDataOneOf6`
     */
    public PayLaterDataOneOf6 getPayLaterDataOneOf6() throws ClassCastException {
        return (PayLaterDataOneOf6)super.getActualInstance();
    }

    /**
     * Get the actual instance of `PayLaterDataOneOf7`. If the actual instance is not `PayLaterDataOneOf7`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `PayLaterDataOneOf7`
     * @throws ClassCastException if the instance is not `PayLaterDataOneOf7`
     */
    public PayLaterDataOneOf7 getPayLaterDataOneOf7() throws ClassCastException {
        return (PayLaterDataOneOf7)super.getActualInstance();
    }



  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    if (getActualInstance() instanceof PayLaterDataOneOf) {
        if (getActualInstance() != null) {
          joiner.add(((PayLaterDataOneOf)getActualInstance()).toUrlQueryString(prefix + "one_of_0" + suffix));
        }
        return joiner.toString();
    }
    if (getActualInstance() instanceof PayLaterDataOneOf1) {
        if (getActualInstance() != null) {
          joiner.add(((PayLaterDataOneOf1)getActualInstance()).toUrlQueryString(prefix + "one_of_1" + suffix));
        }
        return joiner.toString();
    }
    if (getActualInstance() instanceof PayLaterDataOneOf2) {
        if (getActualInstance() != null) {
          joiner.add(((PayLaterDataOneOf2)getActualInstance()).toUrlQueryString(prefix + "one_of_2" + suffix));
        }
        return joiner.toString();
    }
    if (getActualInstance() instanceof PayLaterDataOneOf3) {
        if (getActualInstance() != null) {
          joiner.add(((PayLaterDataOneOf3)getActualInstance()).toUrlQueryString(prefix + "one_of_3" + suffix));
        }
        return joiner.toString();
    }
    if (getActualInstance() instanceof PayLaterDataOneOf4) {
        if (getActualInstance() != null) {
          joiner.add(((PayLaterDataOneOf4)getActualInstance()).toUrlQueryString(prefix + "one_of_4" + suffix));
        }
        return joiner.toString();
    }
    if (getActualInstance() instanceof PayLaterDataOneOf5) {
        if (getActualInstance() != null) {
          joiner.add(((PayLaterDataOneOf5)getActualInstance()).toUrlQueryString(prefix + "one_of_5" + suffix));
        }
        return joiner.toString();
    }
    if (getActualInstance() instanceof PayLaterDataOneOf6) {
        if (getActualInstance() != null) {
          joiner.add(((PayLaterDataOneOf6)getActualInstance()).toUrlQueryString(prefix + "one_of_6" + suffix));
        }
        return joiner.toString();
    }
    if (getActualInstance() instanceof PayLaterDataOneOf7) {
        if (getActualInstance() != null) {
          joiner.add(((PayLaterDataOneOf7)getActualInstance()).toUrlQueryString(prefix + "one_of_7" + suffix));
        }
        return joiner.toString();
    }
    return null;
  }

}

