name: Generate OpenAPI Client

on:
    # Keep existing PR trigger
    pull_request:
        types: [closed]
        paths:
            - 'openapi_spec.json'
    # Add manual trigger
    workflow_dispatch:
        inputs:
            skip_validation:
                description: 'Skip OpenAPI validation'
                type: boolean
                default: false

jobs:
    generate-client:
        if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
        runs-on: ubuntu-latest
        permissions:
            contents: write
            pull-requests: write

        steps:
            - uses: actions/checkout@v3
              with:
                  ref: main

            - name: Validate OpenAPI spec
              if: inputs.skip_validation != true
              id: validate-spec
              continue-on-error: true
              run: |
                  docker run --rm -v "${PWD}:/local" openapitools/openapi-generator-cli validate \
                    -i /local/openapi_spec.json

            - name: Remove Existing Version
              run: |
                  rm -rf ./src/*

            - name: Generate Java Client
              uses: openapi-generators/openapitools-generator-action@v1
              with:
                  generator: java
                  generator-tag: 'v6.5.0'
                  config-file: openai-generator.yml
                  openapi-file: openapi_spec.json
                  command-args: --library feign

            - name: Move generated Files
              run: |
                  mkdir -p src
                  mv java-client/src/main ./src
                  mv java-client/src/test ./src
                  rm -rf java-client

            - name: Create Pull Request
              uses: peter-evans/create-pull-request@v5
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  commit-message: "chore: update Java client from OpenAPI spec"
                  title: "chore: update Java client"
                  body: |
                      Automated PR to update Java client from latest OpenAPI specification.

                      ${{ github.event_name == 'pull_request' && format('Generated from OpenAPI spec version in PR #{0}', github.event.pull_request.number) || 'Generated via manual workflow trigger' }}
                  branch: chore/client-update
                  branch-suffix: timestamp
                  delete-branch: true
                  labels: |
                      client-update
                      automated pr
