/*
 * Hyperswitch - API Documentation
 *  ## Get started  Hyperswitch provides a collection of APIs that enable you to process and manage payments. Our APIs accept and return JSON in the HTTP body, and return standard HTTP response codes.  You can consume the APIs directly using your favorite HTTP/REST library.  We have a testing environment referred to \"sandbox\", which you can setup to test API calls without affecting production data. Currently, our sandbox environment is live while our production environment is under development and will be available soon. You can sign up on our Dashboard to get API keys to access Hyperswitch API.  ### Environment  Use the following base URLs when making requests to the APIs:  | Environment   |  Base URL                          | |---------------|------------------------------------| | Sandbox       | <https://sandbox.hyperswitch.io>   | | Production    | <https://api.hyperswitch.io>       |  ## Authentication  When you sign up on our [dashboard](https://app.hyperswitch.io) and create a merchant account, you are given a secret key (also referred as api-key) and a publishable key. You may authenticate all API requests with Hyperswitch server by providing the appropriate key in the request Authorization header.  | Key             |  Description                                                                                  | |-----------------|-----------------------------------------------------------------------------------------------| | api-key         | Private key. Used to authenticate all API requests from your merchant server                  | | publishable key | Unique identifier for your account. Used to authenticate API requests from your app's client  |  Never share your secret api keys. Keep them guarded and secure. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hyperswitch@juspay.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.hyperswitch.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.hyperswitch.model.BankTransferAdditionalDataOneOf12;
import com.hyperswitch.model.BankTransferDataOneOf;
import com.hyperswitch.model.BankTransferDataOneOf1;
import com.hyperswitch.model.BankTransferDataOneOf10;
import com.hyperswitch.model.BankTransferDataOneOf11;
import com.hyperswitch.model.BankTransferDataOneOf11Pix;
import com.hyperswitch.model.BankTransferDataOneOf12;
import com.hyperswitch.model.BankTransferDataOneOf12LocalBankTransfer;
import com.hyperswitch.model.BankTransferDataOneOf1SepaBankTransfer;
import com.hyperswitch.model.BankTransferDataOneOf2;
import com.hyperswitch.model.BankTransferDataOneOf2BacsBankTransfer;
import com.hyperswitch.model.BankTransferDataOneOf3;
import com.hyperswitch.model.BankTransferDataOneOf3MultibancoBankTransfer;
import com.hyperswitch.model.BankTransferDataOneOf4;
import com.hyperswitch.model.BankTransferDataOneOf4PermataBankTransfer;
import com.hyperswitch.model.BankTransferDataOneOf5;
import com.hyperswitch.model.BankTransferDataOneOf6;
import com.hyperswitch.model.BankTransferDataOneOf7;
import com.hyperswitch.model.BankTransferDataOneOf8;
import com.hyperswitch.model.BankTransferDataOneOf9;
import com.hyperswitch.model.BankTransferDataOneOfAchBankTransfer;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import com.fasterxml.jackson.core.type.TypeReference;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;

import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.JsonToken;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonMappingException;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.MapperFeature;
import com.fasterxml.jackson.databind.SerializerProvider;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;
import com.fasterxml.jackson.databind.ser.std.StdSerializer;
import com.hyperswitch.client.JSON;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.11.0-SNAPSHOT")
@JsonDeserialize(using = BankTransferData.BankTransferDataDeserializer.class)
@JsonSerialize(using = BankTransferData.BankTransferDataSerializer.class)
public class BankTransferData extends AbstractOpenApiSchema {
    private static final Logger log = Logger.getLogger(BankTransferData.class.getName());

    public static class BankTransferDataSerializer extends StdSerializer<BankTransferData> {
        public BankTransferDataSerializer(Class<BankTransferData> t) {
            super(t);
        }

        public BankTransferDataSerializer() {
            this(null);
        }

        @Override
        public void serialize(BankTransferData value, JsonGenerator jgen, SerializerProvider provider) throws IOException, JsonProcessingException {
            jgen.writeObject(value.getActualInstance());
        }
    }

    public static class BankTransferDataDeserializer extends StdDeserializer<BankTransferData> {
        public BankTransferDataDeserializer() {
            this(BankTransferData.class);
        }

        public BankTransferDataDeserializer(Class<?> vc) {
            super(vc);
        }

        @Override
        public BankTransferData deserialize(JsonParser jp, DeserializationContext ctxt) throws IOException, JsonProcessingException {
            JsonNode tree = jp.readValueAsTree();
            Object deserialized = null;
            boolean typeCoercion = ctxt.isEnabled(MapperFeature.ALLOW_COERCION_OF_SCALARS);
            int match = 0;
            JsonToken token = tree.traverse(jp.getCodec()).nextToken();
            // deserialize BankTransferAdditionalDataOneOf12
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (BankTransferAdditionalDataOneOf12.class.equals(Integer.class) || BankTransferAdditionalDataOneOf12.class.equals(Long.class) || BankTransferAdditionalDataOneOf12.class.equals(Float.class) || BankTransferAdditionalDataOneOf12.class.equals(Double.class) || BankTransferAdditionalDataOneOf12.class.equals(Boolean.class) || BankTransferAdditionalDataOneOf12.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((BankTransferAdditionalDataOneOf12.class.equals(Integer.class) || BankTransferAdditionalDataOneOf12.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((BankTransferAdditionalDataOneOf12.class.equals(Float.class) || BankTransferAdditionalDataOneOf12.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (BankTransferAdditionalDataOneOf12.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (BankTransferAdditionalDataOneOf12.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(BankTransferAdditionalDataOneOf12.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'BankTransferAdditionalDataOneOf12'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'BankTransferAdditionalDataOneOf12'", e);
            }

            // deserialize BankTransferDataOneOf
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (BankTransferDataOneOf.class.equals(Integer.class) || BankTransferDataOneOf.class.equals(Long.class) || BankTransferDataOneOf.class.equals(Float.class) || BankTransferDataOneOf.class.equals(Double.class) || BankTransferDataOneOf.class.equals(Boolean.class) || BankTransferDataOneOf.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((BankTransferDataOneOf.class.equals(Integer.class) || BankTransferDataOneOf.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((BankTransferDataOneOf.class.equals(Float.class) || BankTransferDataOneOf.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (BankTransferDataOneOf.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (BankTransferDataOneOf.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(BankTransferDataOneOf.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'BankTransferDataOneOf'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'BankTransferDataOneOf'", e);
            }

            // deserialize BankTransferDataOneOf1
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (BankTransferDataOneOf1.class.equals(Integer.class) || BankTransferDataOneOf1.class.equals(Long.class) || BankTransferDataOneOf1.class.equals(Float.class) || BankTransferDataOneOf1.class.equals(Double.class) || BankTransferDataOneOf1.class.equals(Boolean.class) || BankTransferDataOneOf1.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((BankTransferDataOneOf1.class.equals(Integer.class) || BankTransferDataOneOf1.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((BankTransferDataOneOf1.class.equals(Float.class) || BankTransferDataOneOf1.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (BankTransferDataOneOf1.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (BankTransferDataOneOf1.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(BankTransferDataOneOf1.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'BankTransferDataOneOf1'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'BankTransferDataOneOf1'", e);
            }

            // deserialize BankTransferDataOneOf10
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (BankTransferDataOneOf10.class.equals(Integer.class) || BankTransferDataOneOf10.class.equals(Long.class) || BankTransferDataOneOf10.class.equals(Float.class) || BankTransferDataOneOf10.class.equals(Double.class) || BankTransferDataOneOf10.class.equals(Boolean.class) || BankTransferDataOneOf10.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((BankTransferDataOneOf10.class.equals(Integer.class) || BankTransferDataOneOf10.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((BankTransferDataOneOf10.class.equals(Float.class) || BankTransferDataOneOf10.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (BankTransferDataOneOf10.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (BankTransferDataOneOf10.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(BankTransferDataOneOf10.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'BankTransferDataOneOf10'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'BankTransferDataOneOf10'", e);
            }

            // deserialize BankTransferDataOneOf11
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (BankTransferDataOneOf11.class.equals(Integer.class) || BankTransferDataOneOf11.class.equals(Long.class) || BankTransferDataOneOf11.class.equals(Float.class) || BankTransferDataOneOf11.class.equals(Double.class) || BankTransferDataOneOf11.class.equals(Boolean.class) || BankTransferDataOneOf11.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((BankTransferDataOneOf11.class.equals(Integer.class) || BankTransferDataOneOf11.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((BankTransferDataOneOf11.class.equals(Float.class) || BankTransferDataOneOf11.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (BankTransferDataOneOf11.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (BankTransferDataOneOf11.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(BankTransferDataOneOf11.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'BankTransferDataOneOf11'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'BankTransferDataOneOf11'", e);
            }

            // deserialize BankTransferDataOneOf12
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (BankTransferDataOneOf12.class.equals(Integer.class) || BankTransferDataOneOf12.class.equals(Long.class) || BankTransferDataOneOf12.class.equals(Float.class) || BankTransferDataOneOf12.class.equals(Double.class) || BankTransferDataOneOf12.class.equals(Boolean.class) || BankTransferDataOneOf12.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((BankTransferDataOneOf12.class.equals(Integer.class) || BankTransferDataOneOf12.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((BankTransferDataOneOf12.class.equals(Float.class) || BankTransferDataOneOf12.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (BankTransferDataOneOf12.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (BankTransferDataOneOf12.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(BankTransferDataOneOf12.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'BankTransferDataOneOf12'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'BankTransferDataOneOf12'", e);
            }

            // deserialize BankTransferDataOneOf2
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (BankTransferDataOneOf2.class.equals(Integer.class) || BankTransferDataOneOf2.class.equals(Long.class) || BankTransferDataOneOf2.class.equals(Float.class) || BankTransferDataOneOf2.class.equals(Double.class) || BankTransferDataOneOf2.class.equals(Boolean.class) || BankTransferDataOneOf2.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((BankTransferDataOneOf2.class.equals(Integer.class) || BankTransferDataOneOf2.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((BankTransferDataOneOf2.class.equals(Float.class) || BankTransferDataOneOf2.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (BankTransferDataOneOf2.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (BankTransferDataOneOf2.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(BankTransferDataOneOf2.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'BankTransferDataOneOf2'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'BankTransferDataOneOf2'", e);
            }

            // deserialize BankTransferDataOneOf3
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (BankTransferDataOneOf3.class.equals(Integer.class) || BankTransferDataOneOf3.class.equals(Long.class) || BankTransferDataOneOf3.class.equals(Float.class) || BankTransferDataOneOf3.class.equals(Double.class) || BankTransferDataOneOf3.class.equals(Boolean.class) || BankTransferDataOneOf3.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((BankTransferDataOneOf3.class.equals(Integer.class) || BankTransferDataOneOf3.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((BankTransferDataOneOf3.class.equals(Float.class) || BankTransferDataOneOf3.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (BankTransferDataOneOf3.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (BankTransferDataOneOf3.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(BankTransferDataOneOf3.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'BankTransferDataOneOf3'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'BankTransferDataOneOf3'", e);
            }

            // deserialize BankTransferDataOneOf4
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (BankTransferDataOneOf4.class.equals(Integer.class) || BankTransferDataOneOf4.class.equals(Long.class) || BankTransferDataOneOf4.class.equals(Float.class) || BankTransferDataOneOf4.class.equals(Double.class) || BankTransferDataOneOf4.class.equals(Boolean.class) || BankTransferDataOneOf4.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((BankTransferDataOneOf4.class.equals(Integer.class) || BankTransferDataOneOf4.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((BankTransferDataOneOf4.class.equals(Float.class) || BankTransferDataOneOf4.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (BankTransferDataOneOf4.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (BankTransferDataOneOf4.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(BankTransferDataOneOf4.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'BankTransferDataOneOf4'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'BankTransferDataOneOf4'", e);
            }

            // deserialize BankTransferDataOneOf5
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (BankTransferDataOneOf5.class.equals(Integer.class) || BankTransferDataOneOf5.class.equals(Long.class) || BankTransferDataOneOf5.class.equals(Float.class) || BankTransferDataOneOf5.class.equals(Double.class) || BankTransferDataOneOf5.class.equals(Boolean.class) || BankTransferDataOneOf5.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((BankTransferDataOneOf5.class.equals(Integer.class) || BankTransferDataOneOf5.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((BankTransferDataOneOf5.class.equals(Float.class) || BankTransferDataOneOf5.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (BankTransferDataOneOf5.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (BankTransferDataOneOf5.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(BankTransferDataOneOf5.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'BankTransferDataOneOf5'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'BankTransferDataOneOf5'", e);
            }

            // deserialize BankTransferDataOneOf6
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (BankTransferDataOneOf6.class.equals(Integer.class) || BankTransferDataOneOf6.class.equals(Long.class) || BankTransferDataOneOf6.class.equals(Float.class) || BankTransferDataOneOf6.class.equals(Double.class) || BankTransferDataOneOf6.class.equals(Boolean.class) || BankTransferDataOneOf6.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((BankTransferDataOneOf6.class.equals(Integer.class) || BankTransferDataOneOf6.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((BankTransferDataOneOf6.class.equals(Float.class) || BankTransferDataOneOf6.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (BankTransferDataOneOf6.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (BankTransferDataOneOf6.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(BankTransferDataOneOf6.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'BankTransferDataOneOf6'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'BankTransferDataOneOf6'", e);
            }

            // deserialize BankTransferDataOneOf7
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (BankTransferDataOneOf7.class.equals(Integer.class) || BankTransferDataOneOf7.class.equals(Long.class) || BankTransferDataOneOf7.class.equals(Float.class) || BankTransferDataOneOf7.class.equals(Double.class) || BankTransferDataOneOf7.class.equals(Boolean.class) || BankTransferDataOneOf7.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((BankTransferDataOneOf7.class.equals(Integer.class) || BankTransferDataOneOf7.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((BankTransferDataOneOf7.class.equals(Float.class) || BankTransferDataOneOf7.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (BankTransferDataOneOf7.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (BankTransferDataOneOf7.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(BankTransferDataOneOf7.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'BankTransferDataOneOf7'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'BankTransferDataOneOf7'", e);
            }

            // deserialize BankTransferDataOneOf8
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (BankTransferDataOneOf8.class.equals(Integer.class) || BankTransferDataOneOf8.class.equals(Long.class) || BankTransferDataOneOf8.class.equals(Float.class) || BankTransferDataOneOf8.class.equals(Double.class) || BankTransferDataOneOf8.class.equals(Boolean.class) || BankTransferDataOneOf8.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((BankTransferDataOneOf8.class.equals(Integer.class) || BankTransferDataOneOf8.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((BankTransferDataOneOf8.class.equals(Float.class) || BankTransferDataOneOf8.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (BankTransferDataOneOf8.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (BankTransferDataOneOf8.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(BankTransferDataOneOf8.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'BankTransferDataOneOf8'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'BankTransferDataOneOf8'", e);
            }

            // deserialize BankTransferDataOneOf9
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (BankTransferDataOneOf9.class.equals(Integer.class) || BankTransferDataOneOf9.class.equals(Long.class) || BankTransferDataOneOf9.class.equals(Float.class) || BankTransferDataOneOf9.class.equals(Double.class) || BankTransferDataOneOf9.class.equals(Boolean.class) || BankTransferDataOneOf9.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((BankTransferDataOneOf9.class.equals(Integer.class) || BankTransferDataOneOf9.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((BankTransferDataOneOf9.class.equals(Float.class) || BankTransferDataOneOf9.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (BankTransferDataOneOf9.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (BankTransferDataOneOf9.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(BankTransferDataOneOf9.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'BankTransferDataOneOf9'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'BankTransferDataOneOf9'", e);
            }

            if (match == 1) {
                BankTransferData ret = new BankTransferData();
                ret.setActualInstance(deserialized);
                return ret;
            }
            throw new IOException(String.format("Failed deserialization for BankTransferData: %d classes match result, expected 1", match));
        }

        /**
         * Handle deserialization of the 'null' value.
         */
        @Override
        public BankTransferData getNullValue(DeserializationContext ctxt) throws JsonMappingException {
            throw new JsonMappingException(ctxt.getParser(), "BankTransferData cannot be null");
        }
    }

    // store a list of schema names defined in oneOf
    public static final Map<String, Class<?>> schemas = new HashMap<>();

    public BankTransferData() {
        super("oneOf", Boolean.FALSE);
    }

    public BankTransferData(BankTransferAdditionalDataOneOf12 o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public BankTransferData(BankTransferDataOneOf o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public BankTransferData(BankTransferDataOneOf1 o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public BankTransferData(BankTransferDataOneOf10 o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public BankTransferData(BankTransferDataOneOf11 o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public BankTransferData(BankTransferDataOneOf12 o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public BankTransferData(BankTransferDataOneOf2 o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public BankTransferData(BankTransferDataOneOf3 o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public BankTransferData(BankTransferDataOneOf4 o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public BankTransferData(BankTransferDataOneOf5 o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public BankTransferData(BankTransferDataOneOf6 o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public BankTransferData(BankTransferDataOneOf7 o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public BankTransferData(BankTransferDataOneOf8 o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public BankTransferData(BankTransferDataOneOf9 o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    static {
        schemas.put("BankTransferAdditionalDataOneOf12", BankTransferAdditionalDataOneOf12.class);
        schemas.put("BankTransferDataOneOf", BankTransferDataOneOf.class);
        schemas.put("BankTransferDataOneOf1", BankTransferDataOneOf1.class);
        schemas.put("BankTransferDataOneOf10", BankTransferDataOneOf10.class);
        schemas.put("BankTransferDataOneOf11", BankTransferDataOneOf11.class);
        schemas.put("BankTransferDataOneOf12", BankTransferDataOneOf12.class);
        schemas.put("BankTransferDataOneOf2", BankTransferDataOneOf2.class);
        schemas.put("BankTransferDataOneOf3", BankTransferDataOneOf3.class);
        schemas.put("BankTransferDataOneOf4", BankTransferDataOneOf4.class);
        schemas.put("BankTransferDataOneOf5", BankTransferDataOneOf5.class);
        schemas.put("BankTransferDataOneOf6", BankTransferDataOneOf6.class);
        schemas.put("BankTransferDataOneOf7", BankTransferDataOneOf7.class);
        schemas.put("BankTransferDataOneOf8", BankTransferDataOneOf8.class);
        schemas.put("BankTransferDataOneOf9", BankTransferDataOneOf9.class);
        JSON.registerDescendants(BankTransferData.class, Collections.unmodifiableMap(schemas));
    }

    @Override
    public Map<String, Class<?>> getSchemas() {
        return BankTransferData.schemas;
    }

    /**
     * Set the instance that matches the oneOf child schema, check
     * the instance parameter is valid against the oneOf child schemas:
     * BankTransferAdditionalDataOneOf12, BankTransferDataOneOf, BankTransferDataOneOf1, BankTransferDataOneOf10, BankTransferDataOneOf11, BankTransferDataOneOf12, BankTransferDataOneOf2, BankTransferDataOneOf3, BankTransferDataOneOf4, BankTransferDataOneOf5, BankTransferDataOneOf6, BankTransferDataOneOf7, BankTransferDataOneOf8, BankTransferDataOneOf9
     *
     * It could be an instance of the 'oneOf' schemas.
     * The oneOf child schemas may themselves be a composed schema (allOf, anyOf, oneOf).
     */
    @Override
    public void setActualInstance(Object instance) {
        if (JSON.isInstanceOf(BankTransferAdditionalDataOneOf12.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(BankTransferDataOneOf.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(BankTransferDataOneOf1.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(BankTransferDataOneOf10.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(BankTransferDataOneOf11.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(BankTransferDataOneOf12.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(BankTransferDataOneOf2.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(BankTransferDataOneOf3.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(BankTransferDataOneOf4.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(BankTransferDataOneOf5.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(BankTransferDataOneOf6.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(BankTransferDataOneOf7.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(BankTransferDataOneOf8.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(BankTransferDataOneOf9.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        throw new RuntimeException("Invalid instance type. Must be BankTransferAdditionalDataOneOf12, BankTransferDataOneOf, BankTransferDataOneOf1, BankTransferDataOneOf10, BankTransferDataOneOf11, BankTransferDataOneOf12, BankTransferDataOneOf2, BankTransferDataOneOf3, BankTransferDataOneOf4, BankTransferDataOneOf5, BankTransferDataOneOf6, BankTransferDataOneOf7, BankTransferDataOneOf8, BankTransferDataOneOf9");
    }

    /**
     * Get the actual instance, which can be the following:
     * BankTransferAdditionalDataOneOf12, BankTransferDataOneOf, BankTransferDataOneOf1, BankTransferDataOneOf10, BankTransferDataOneOf11, BankTransferDataOneOf12, BankTransferDataOneOf2, BankTransferDataOneOf3, BankTransferDataOneOf4, BankTransferDataOneOf5, BankTransferDataOneOf6, BankTransferDataOneOf7, BankTransferDataOneOf8, BankTransferDataOneOf9
     *
     * @return The actual instance (BankTransferAdditionalDataOneOf12, BankTransferDataOneOf, BankTransferDataOneOf1, BankTransferDataOneOf10, BankTransferDataOneOf11, BankTransferDataOneOf12, BankTransferDataOneOf2, BankTransferDataOneOf3, BankTransferDataOneOf4, BankTransferDataOneOf5, BankTransferDataOneOf6, BankTransferDataOneOf7, BankTransferDataOneOf8, BankTransferDataOneOf9)
     */
    @Override
    public Object getActualInstance() {
        return super.getActualInstance();
    }

    /**
     * Get the actual instance of `BankTransferAdditionalDataOneOf12`. If the actual instance is not `BankTransferAdditionalDataOneOf12`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `BankTransferAdditionalDataOneOf12`
     * @throws ClassCastException if the instance is not `BankTransferAdditionalDataOneOf12`
     */
    public BankTransferAdditionalDataOneOf12 getBankTransferAdditionalDataOneOf12() throws ClassCastException {
        return (BankTransferAdditionalDataOneOf12)super.getActualInstance();
    }

    /**
     * Get the actual instance of `BankTransferDataOneOf`. If the actual instance is not `BankTransferDataOneOf`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `BankTransferDataOneOf`
     * @throws ClassCastException if the instance is not `BankTransferDataOneOf`
     */
    public BankTransferDataOneOf getBankTransferDataOneOf() throws ClassCastException {
        return (BankTransferDataOneOf)super.getActualInstance();
    }

    /**
     * Get the actual instance of `BankTransferDataOneOf1`. If the actual instance is not `BankTransferDataOneOf1`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `BankTransferDataOneOf1`
     * @throws ClassCastException if the instance is not `BankTransferDataOneOf1`
     */
    public BankTransferDataOneOf1 getBankTransferDataOneOf1() throws ClassCastException {
        return (BankTransferDataOneOf1)super.getActualInstance();
    }

    /**
     * Get the actual instance of `BankTransferDataOneOf10`. If the actual instance is not `BankTransferDataOneOf10`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `BankTransferDataOneOf10`
     * @throws ClassCastException if the instance is not `BankTransferDataOneOf10`
     */
    public BankTransferDataOneOf10 getBankTransferDataOneOf10() throws ClassCastException {
        return (BankTransferDataOneOf10)super.getActualInstance();
    }

    /**
     * Get the actual instance of `BankTransferDataOneOf11`. If the actual instance is not `BankTransferDataOneOf11`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `BankTransferDataOneOf11`
     * @throws ClassCastException if the instance is not `BankTransferDataOneOf11`
     */
    public BankTransferDataOneOf11 getBankTransferDataOneOf11() throws ClassCastException {
        return (BankTransferDataOneOf11)super.getActualInstance();
    }

    /**
     * Get the actual instance of `BankTransferDataOneOf12`. If the actual instance is not `BankTransferDataOneOf12`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `BankTransferDataOneOf12`
     * @throws ClassCastException if the instance is not `BankTransferDataOneOf12`
     */
    public BankTransferDataOneOf12 getBankTransferDataOneOf12() throws ClassCastException {
        return (BankTransferDataOneOf12)super.getActualInstance();
    }

    /**
     * Get the actual instance of `BankTransferDataOneOf2`. If the actual instance is not `BankTransferDataOneOf2`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `BankTransferDataOneOf2`
     * @throws ClassCastException if the instance is not `BankTransferDataOneOf2`
     */
    public BankTransferDataOneOf2 getBankTransferDataOneOf2() throws ClassCastException {
        return (BankTransferDataOneOf2)super.getActualInstance();
    }

    /**
     * Get the actual instance of `BankTransferDataOneOf3`. If the actual instance is not `BankTransferDataOneOf3`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `BankTransferDataOneOf3`
     * @throws ClassCastException if the instance is not `BankTransferDataOneOf3`
     */
    public BankTransferDataOneOf3 getBankTransferDataOneOf3() throws ClassCastException {
        return (BankTransferDataOneOf3)super.getActualInstance();
    }

    /**
     * Get the actual instance of `BankTransferDataOneOf4`. If the actual instance is not `BankTransferDataOneOf4`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `BankTransferDataOneOf4`
     * @throws ClassCastException if the instance is not `BankTransferDataOneOf4`
     */
    public BankTransferDataOneOf4 getBankTransferDataOneOf4() throws ClassCastException {
        return (BankTransferDataOneOf4)super.getActualInstance();
    }

    /**
     * Get the actual instance of `BankTransferDataOneOf5`. If the actual instance is not `BankTransferDataOneOf5`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `BankTransferDataOneOf5`
     * @throws ClassCastException if the instance is not `BankTransferDataOneOf5`
     */
    public BankTransferDataOneOf5 getBankTransferDataOneOf5() throws ClassCastException {
        return (BankTransferDataOneOf5)super.getActualInstance();
    }

    /**
     * Get the actual instance of `BankTransferDataOneOf6`. If the actual instance is not `BankTransferDataOneOf6`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `BankTransferDataOneOf6`
     * @throws ClassCastException if the instance is not `BankTransferDataOneOf6`
     */
    public BankTransferDataOneOf6 getBankTransferDataOneOf6() throws ClassCastException {
        return (BankTransferDataOneOf6)super.getActualInstance();
    }

    /**
     * Get the actual instance of `BankTransferDataOneOf7`. If the actual instance is not `BankTransferDataOneOf7`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `BankTransferDataOneOf7`
     * @throws ClassCastException if the instance is not `BankTransferDataOneOf7`
     */
    public BankTransferDataOneOf7 getBankTransferDataOneOf7() throws ClassCastException {
        return (BankTransferDataOneOf7)super.getActualInstance();
    }

    /**
     * Get the actual instance of `BankTransferDataOneOf8`. If the actual instance is not `BankTransferDataOneOf8`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `BankTransferDataOneOf8`
     * @throws ClassCastException if the instance is not `BankTransferDataOneOf8`
     */
    public BankTransferDataOneOf8 getBankTransferDataOneOf8() throws ClassCastException {
        return (BankTransferDataOneOf8)super.getActualInstance();
    }

    /**
     * Get the actual instance of `BankTransferDataOneOf9`. If the actual instance is not `BankTransferDataOneOf9`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `BankTransferDataOneOf9`
     * @throws ClassCastException if the instance is not `BankTransferDataOneOf9`
     */
    public BankTransferDataOneOf9 getBankTransferDataOneOf9() throws ClassCastException {
        return (BankTransferDataOneOf9)super.getActualInstance();
    }



  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    if (getActualInstance() instanceof BankTransferDataOneOf) {
        if (getActualInstance() != null) {
          joiner.add(((BankTransferDataOneOf)getActualInstance()).toUrlQueryString(prefix + "one_of_0" + suffix));
        }
        return joiner.toString();
    }
    if (getActualInstance() instanceof BankTransferDataOneOf1) {
        if (getActualInstance() != null) {
          joiner.add(((BankTransferDataOneOf1)getActualInstance()).toUrlQueryString(prefix + "one_of_1" + suffix));
        }
        return joiner.toString();
    }
    if (getActualInstance() instanceof BankTransferDataOneOf2) {
        if (getActualInstance() != null) {
          joiner.add(((BankTransferDataOneOf2)getActualInstance()).toUrlQueryString(prefix + "one_of_2" + suffix));
        }
        return joiner.toString();
    }
    if (getActualInstance() instanceof BankTransferDataOneOf3) {
        if (getActualInstance() != null) {
          joiner.add(((BankTransferDataOneOf3)getActualInstance()).toUrlQueryString(prefix + "one_of_3" + suffix));
        }
        return joiner.toString();
    }
    if (getActualInstance() instanceof BankTransferDataOneOf4) {
        if (getActualInstance() != null) {
          joiner.add(((BankTransferDataOneOf4)getActualInstance()).toUrlQueryString(prefix + "one_of_4" + suffix));
        }
        return joiner.toString();
    }
    if (getActualInstance() instanceof BankTransferDataOneOf5) {
        if (getActualInstance() != null) {
          joiner.add(((BankTransferDataOneOf5)getActualInstance()).toUrlQueryString(prefix + "one_of_5" + suffix));
        }
        return joiner.toString();
    }
    if (getActualInstance() instanceof BankTransferDataOneOf6) {
        if (getActualInstance() != null) {
          joiner.add(((BankTransferDataOneOf6)getActualInstance()).toUrlQueryString(prefix + "one_of_6" + suffix));
        }
        return joiner.toString();
    }
    if (getActualInstance() instanceof BankTransferDataOneOf7) {
        if (getActualInstance() != null) {
          joiner.add(((BankTransferDataOneOf7)getActualInstance()).toUrlQueryString(prefix + "one_of_7" + suffix));
        }
        return joiner.toString();
    }
    if (getActualInstance() instanceof BankTransferDataOneOf8) {
        if (getActualInstance() != null) {
          joiner.add(((BankTransferDataOneOf8)getActualInstance()).toUrlQueryString(prefix + "one_of_8" + suffix));
        }
        return joiner.toString();
    }
    if (getActualInstance() instanceof BankTransferDataOneOf9) {
        if (getActualInstance() != null) {
          joiner.add(((BankTransferDataOneOf9)getActualInstance()).toUrlQueryString(prefix + "one_of_9" + suffix));
        }
        return joiner.toString();
    }
    if (getActualInstance() instanceof BankTransferDataOneOf10) {
        if (getActualInstance() != null) {
          joiner.add(((BankTransferDataOneOf10)getActualInstance()).toUrlQueryString(prefix + "one_of_10" + suffix));
        }
        return joiner.toString();
    }
    if (getActualInstance() instanceof BankTransferDataOneOf11) {
        if (getActualInstance() != null) {
          joiner.add(((BankTransferDataOneOf11)getActualInstance()).toUrlQueryString(prefix + "one_of_11" + suffix));
        }
        return joiner.toString();
    }
    if (getActualInstance() instanceof BankTransferAdditionalDataOneOf12) {
        if (getActualInstance() != null) {
          joiner.add(((BankTransferAdditionalDataOneOf12)getActualInstance()).toUrlQueryString(prefix + "one_of_12" + suffix));
        }
        return joiner.toString();
    }
    if (getActualInstance() instanceof BankTransferDataOneOf12) {
        if (getActualInstance() != null) {
          joiner.add(((BankTransferDataOneOf12)getActualInstance()).toUrlQueryString(prefix + "one_of_13" + suffix));
        }
        return joiner.toString();
    }
    return null;
  }

}

