/*
 * Hyperswitch - API Documentation
 *  ## Get started  Hyperswitch provides a collection of APIs that enable you to process and manage payments. Our APIs accept and return JSON in the HTTP body, and return standard HTTP response codes.  You can consume the APIs directly using your favorite HTTP/REST library.  We have a testing environment referred to \"sandbox\", which you can setup to test API calls without affecting production data. Currently, our sandbox environment is live while our production environment is under development and will be available soon. You can sign up on our Dashboard to get API keys to access Hyperswitch API.  ### Environment  Use the following base URLs when making requests to the APIs:  | Environment   |  Base URL                          | |---------------|------------------------------------| | Sandbox       | <https://sandbox.hyperswitch.io>   | | Production    | <https://api.hyperswitch.io>       |  ## Authentication  When you sign up on our [dashboard](https://app.hyperswitch.io) and create a merchant account, you are given a secret key (also referred as api-key) and a publishable key. You may authenticate all API requests with Hyperswitch server by providing the appropriate key in the request Authorization header.  | Key             |  Description                                                                                  | |-----------------|-----------------------------------------------------------------------------------------------| | api-key         | Private key. Used to authenticate all API requests from your merchant server                  | | publishable key | Unique identifier for your account. Used to authenticate API requests from your app's client  |  Never share your secret api keys. Keep them guarded and secure. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: hyperswitch@juspay.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.hyperswitch.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.hyperswitch.model.ConnectorVolumeSplit;
import com.hyperswitch.model.Priority;
import com.hyperswitch.model.Single;
import com.hyperswitch.model.VolumeSplit;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import com.fasterxml.jackson.core.type.TypeReference;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;

import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.JsonToken;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonMappingException;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.MapperFeature;
import com.fasterxml.jackson.databind.SerializerProvider;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;
import com.fasterxml.jackson.databind.ser.std.StdSerializer;
import com.hyperswitch.client.JSON;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.11.0-SNAPSHOT")
@JsonDeserialize(using = StraightThroughAlgorithm.StraightThroughAlgorithmDeserializer.class)
@JsonSerialize(using = StraightThroughAlgorithm.StraightThroughAlgorithmSerializer.class)
public class StraightThroughAlgorithm extends AbstractOpenApiSchema {
    private static final Logger log = Logger.getLogger(StraightThroughAlgorithm.class.getName());

    public static class StraightThroughAlgorithmSerializer extends StdSerializer<StraightThroughAlgorithm> {
        public StraightThroughAlgorithmSerializer(Class<StraightThroughAlgorithm> t) {
            super(t);
        }

        public StraightThroughAlgorithmSerializer() {
            this(null);
        }

        @Override
        public void serialize(StraightThroughAlgorithm value, JsonGenerator jgen, SerializerProvider provider) throws IOException, JsonProcessingException {
            jgen.writeObject(value.getActualInstance());
        }
    }

    public static class StraightThroughAlgorithmDeserializer extends StdDeserializer<StraightThroughAlgorithm> {
        public StraightThroughAlgorithmDeserializer() {
            this(StraightThroughAlgorithm.class);
        }

        public StraightThroughAlgorithmDeserializer(Class<?> vc) {
            super(vc);
        }

        @Override
        public StraightThroughAlgorithm deserialize(JsonParser jp, DeserializationContext ctxt) throws IOException, JsonProcessingException {
            JsonNode tree = jp.readValueAsTree();
            Object deserialized = null;
            boolean typeCoercion = ctxt.isEnabled(MapperFeature.ALLOW_COERCION_OF_SCALARS);
            int match = 0;
            JsonToken token = tree.traverse(jp.getCodec()).nextToken();
            // deserialize Priority
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (Priority.class.equals(Integer.class) || Priority.class.equals(Long.class) || Priority.class.equals(Float.class) || Priority.class.equals(Double.class) || Priority.class.equals(Boolean.class) || Priority.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((Priority.class.equals(Integer.class) || Priority.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((Priority.class.equals(Float.class) || Priority.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (Priority.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (Priority.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(Priority.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'Priority'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'Priority'", e);
            }

            // deserialize Single
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (Single.class.equals(Integer.class) || Single.class.equals(Long.class) || Single.class.equals(Float.class) || Single.class.equals(Double.class) || Single.class.equals(Boolean.class) || Single.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((Single.class.equals(Integer.class) || Single.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((Single.class.equals(Float.class) || Single.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (Single.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (Single.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(Single.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'Single'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'Single'", e);
            }

            // deserialize VolumeSplit
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (VolumeSplit.class.equals(Integer.class) || VolumeSplit.class.equals(Long.class) || VolumeSplit.class.equals(Float.class) || VolumeSplit.class.equals(Double.class) || VolumeSplit.class.equals(Boolean.class) || VolumeSplit.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((VolumeSplit.class.equals(Integer.class) || VolumeSplit.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((VolumeSplit.class.equals(Float.class) || VolumeSplit.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (VolumeSplit.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (VolumeSplit.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(VolumeSplit.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'VolumeSplit'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'VolumeSplit'", e);
            }

            if (match == 1) {
                StraightThroughAlgorithm ret = new StraightThroughAlgorithm();
                ret.setActualInstance(deserialized);
                return ret;
            }
            throw new IOException(String.format("Failed deserialization for StraightThroughAlgorithm: %d classes match result, expected 1", match));
        }

        /**
         * Handle deserialization of the 'null' value.
         */
        @Override
        public StraightThroughAlgorithm getNullValue(DeserializationContext ctxt) throws JsonMappingException {
            throw new JsonMappingException(ctxt.getParser(), "StraightThroughAlgorithm cannot be null");
        }
    }

    // store a list of schema names defined in oneOf
    public static final Map<String, Class<?>> schemas = new HashMap<>();

    public StraightThroughAlgorithm() {
        super("oneOf", Boolean.FALSE);
    }

    public StraightThroughAlgorithm(Priority o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public StraightThroughAlgorithm(Single o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public StraightThroughAlgorithm(VolumeSplit o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    static {
        schemas.put("Priority", Priority.class);
        schemas.put("Single", Single.class);
        schemas.put("VolumeSplit", VolumeSplit.class);
        JSON.registerDescendants(StraightThroughAlgorithm.class, Collections.unmodifiableMap(schemas));
        // Initialize and register the discriminator mappings.
        Map<String, Class<?>> mappings = new HashMap<String, Class<?>>();
        mappings.put("Priority", Priority.class);
        mappings.put("Single", Single.class);
        mappings.put("VolumeSplit", VolumeSplit.class);
        mappings.put("StraightThroughAlgorithm", StraightThroughAlgorithm.class);
        JSON.registerDiscriminator(StraightThroughAlgorithm.class, "type", mappings);
    }

    @Override
    public Map<String, Class<?>> getSchemas() {
        return StraightThroughAlgorithm.schemas;
    }

    /**
     * Set the instance that matches the oneOf child schema, check
     * the instance parameter is valid against the oneOf child schemas:
     * Priority, Single, VolumeSplit
     *
     * It could be an instance of the 'oneOf' schemas.
     * The oneOf child schemas may themselves be a composed schema (allOf, anyOf, oneOf).
     */
    @Override
    public void setActualInstance(Object instance) {
        if (JSON.isInstanceOf(Priority.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(Single.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(VolumeSplit.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        throw new RuntimeException("Invalid instance type. Must be Priority, Single, VolumeSplit");
    }

    /**
     * Get the actual instance, which can be the following:
     * Priority, Single, VolumeSplit
     *
     * @return The actual instance (Priority, Single, VolumeSplit)
     */
    @Override
    public Object getActualInstance() {
        return super.getActualInstance();
    }

    /**
     * Get the actual instance of `Priority`. If the actual instance is not `Priority`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `Priority`
     * @throws ClassCastException if the instance is not `Priority`
     */
    public Priority getPriority() throws ClassCastException {
        return (Priority)super.getActualInstance();
    }

    /**
     * Get the actual instance of `Single`. If the actual instance is not `Single`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `Single`
     * @throws ClassCastException if the instance is not `Single`
     */
    public Single getSingle() throws ClassCastException {
        return (Single)super.getActualInstance();
    }

    /**
     * Get the actual instance of `VolumeSplit`. If the actual instance is not `VolumeSplit`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `VolumeSplit`
     * @throws ClassCastException if the instance is not `VolumeSplit`
     */
    public VolumeSplit getVolumeSplit() throws ClassCastException {
        return (VolumeSplit)super.getActualInstance();
    }



  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    if (getActualInstance() instanceof Single) {
        if (getActualInstance() != null) {
          joiner.add(((Single)getActualInstance()).toUrlQueryString(prefix + "one_of_0" + suffix));
        }
        return joiner.toString();
    }
    if (getActualInstance() instanceof Priority) {
        if (getActualInstance() != null) {
          joiner.add(((Priority)getActualInstance()).toUrlQueryString(prefix + "one_of_1" + suffix));
        }
        return joiner.toString();
    }
    if (getActualInstance() instanceof VolumeSplit) {
        if (getActualInstance() != null) {
          joiner.add(((VolumeSplit)getActualInstance()).toUrlQueryString(prefix + "one_of_2" + suffix));
        }
        return joiner.toString();
    }
    return null;
  }

}

